language: python
sudo: required
python:
    - 2.7
virtualenv:
    system_site_packages: true
install:
    - sudo apt-get install python-pygame
    - pip install coverage coveralls -e .
script:
    - coverage run --source=src/pyspacewar test.py
after_success:
    - coveralls
notifications:
    email: false
