language: python
sudo: required
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
matrix:
    include:
        - python: 3.7
          dist: xenial
before_install:
    - sudo apt-get update -q
    - sudo apt-get build-dep -y python-pygame
    - pip install -U pip
install:
    - pip install coverage coveralls -e .
script:
    - coverage run test.py
after_success:
    - coveralls
notifications:
    email: false
