language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
install:
    - pip install -U pip
    - pip install coverage coveralls -e .
script:
    - coverage run --source=src/pyspacewar test.py
after_success:
    - coveralls
notifications:
    email: false
