language: python
cache: pip
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - pypy
  - pypy3
addons:
  apt:
    packages:
      - fontconfig
      - libfreetype6-dev
      - libjpeg-dev
      - libpng-dev
      - libportmidi-dev
      # pygame 2.0 needs SDL 2
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
before_install:
  - pip install -U pip
  - |
    include_dir=/home/travis/virtualenv/$TRAVIS_PYTHON_VERSION/include
    if [ -L $include_dir ]; then
      # pygame tries to install stuff into $include_dir/site/pygame,
      # which will not work if $include_dir is a symlink to a read-only
      # system-wide include dir as is the case for pypy and pypy3
      # (but not cpython for some reason)
      real_include_dir=$(readlink $include_dir)
      rm $include_dir
      cp -r $real_include_dir $include_dir
    fi
install:
  - pip install coverage coveralls -e .
script:
  - coverage run -m pytest src
after_success:
  - coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net##mgedmin"
    on_success: change
    on_failure: always
    template:
      # ping my nick so I get a pushbullet notification on my phone
      - "mgedmin: %{repository_name} (%{branch}) build %{result}: %{build_url}"
